### ISSUE TITLE
Thoughts on including `Subrequester` implementations for composite API calls?

### ISSUE THREAD

**Issue by nyergler** [namely/go-sfdc#12]
I'm using `go-sfdc` for interacting with Salesforce's APIs in our product, and am curious about the maintainer's thoughts on including built in support for more calls.

Specifically, the `composite` and `batch` packages provide interfaces for managing combined requests, but there are many calls which don't have implementations in the package. For example, we're interested in checking the state of an organizations [limits](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm) before proceeding with processing, and that's something that can naturally fit into a composite (batch) request.

I have an initial implementation of a Limits sub-request on [a branch in my fork](https://github.com/polytomic/go-sfdc/tree/limits), and I'm wondering if this is something the maintainers think is suitable for inclusion upstream. If not, I'll probably refactor it out of our fork so we can track upstream. However, it feels like something that might be useful for others, and seems unlikely to vary much between implementations.

Thoughts?

**Comment by vtopc** [comment]
Sounds good.

**Comment by nyergler** [comment]
Closing this, as we've established this is appropriate for inclusion and are working through the PR in #13
